name: generate snake

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate snake svgs
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=0891B2&color_dots=EBEDF0,C4B5FD,8B5CF6,7C3AED,06B6D4
            dist/github-contribution-grid-snake-dark.svg?color_snake=22D3EE&color_dots=1F2937,4C1D95,7C3AED,A78BFA,22D3EE

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
