name: generate snake

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
      - develop
  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: generate snake svgs
        uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=%230891B2&color_dots=%23EBEDF0,%23C4B5FD,%238B5CF6,%237C3AED,%2306B6D4
            dist/github-contribution-grid-snake-dark.svg?color_snake=%2322D3EE&color_dots=%231F2937,%234C1D95,%237C3AED,%23A78BFA,%2322D3EE

      - name: push to output branch
        uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
